# Generated by Django 4.2.1 on 2023-06-20 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweetLand', '0002_comment_likes_comment_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='tweet_pic',
            field=models.ImageField(blank=True, null=True, upload_to='images/tweets'),
        ),
    ]
