# Generated by Django 4.2.1 on 2023-06-30 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweetLand', '0003_tweet_tweet_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_background',
            field=models.ImageField(blank=True, null=True, upload_to='profile_bg/'),
        ),
    ]
